language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t anojkunes1994/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true anojkunes1994/react-test npm run test

after_success:
  - docker build -t  anojkunes1994/multi-client ./client
  - docker build -t  anojkunes1994/multi-nginx ./nginx
  - docker build -t  anojkunes1994/multi-server ./server
  - docker build -t  anojkunes1994/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push anojkunes1994/multi-client
  - docker push anojkunes1994/multi-nginx
  - docker push anojkunes1994/multi-server
  - docker push anojkunes1994/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-eu-west-2-950436335228"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY